# Generated by Django 4.1.7 on 2023-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpesa_payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaResponseBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
